name: "Lake Como | Sotheby's International Realty"
favicon: null
layout_spectrum: 0.08806
typography_spectrum: 0.90576
title: 'Diego Antinolo | Real Estate Professional '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c1c1c9'
    - '#010101'
    - '#4d728f'
    - '#003789'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
