name: "Diego Antinolo | Sotheby's Realty"
favicon: null
layout_spectrum: 0.3323497758246958
typography_spectrum: 0.16975356894545257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4814532462041825
  lightness: 0.5056812844704837
  saturation: 0.47559341439045966
  rhythmicContrast: 0.9535705333109945
purpose: []
